# Sounds 01..15 relate to level bgm

[01]
file       = "resources/audio/bgm/titlescreen.ogg"

[02]
file       = "resources/audio/bgm/youre_my_hero.ogg"
loop-start = 6.937
loop-end   = 96.111

[03]
file       = "resources/audio/bgm/transparenthighway.ogg"
loop-start = 45.459
loop-end   = 124.528

[04]
file       = "resources/audio/bgm/enjoythisworld.ogg"
loop-start = 0.049
loop-end   = 111.671

[05]
file       = "resources/audio/bgm/amazingaquarium.ogg"
loop-start = 11.009
loop-end   = 87.848

[06]
file       = "resources/audio/bgm/cybercity.ogg"
loop-start = 6.438
loop-end   = 67.231

[07]
file       = "resources/audio/bgm/walkin.ogg"
loop-start = 1.080
loop-end   = 17.233

[08]
file       = "resources/audio/bgm/chaoticcanyon.ogg"
loop-start = 8.799
loop-end   = 78.616

[09]
file       = "resources/audio/bgm/hyperhyper.ogg"
loop-start = 11.351
loop-end   = 41.420

[0A]
file       = "resources/audio/bgm/hiddenpalace.ogg"
loop-start = 0.612
loop-end   = 52.679

[0B]
file       = "resources/audio/bgm/speedslider.ogg"
loop-start = 0.075
loop-end   = 72.077

# [0C]
# [0D]
# [0E]
# [0F]
# [10]
# [11]
# [12]
# [13]
# [14]
# [15]

[16]
file = "resources/audio/sfx/skidding.ogg"

[17]
file = "resources/audio/sfx/rolling.ogg"

[18]
file = "resources/audio/sfx/jump.ogg"

[19]
file = "resources/audio/sfx/spindash.ogg"

[1A]
file = "resources/audio/sfx/release.ogg"

[1B]
file = "resources/audio/sfx/splash.ogg"

[1C]
file = "resources/audio/sfx/normalshield.ogg"

[1D]
file = "resources/audio/sfx/bubbleshield.ogg"

[1E]
file = "resources/audio/sfx/watercount.ogg"

[1F]
file = "resources/audio/sfx/bubbleget.ogg"

[20]
file = "resources/audio/sfx/drown.ogg"

[21]
file = "resources/audio/sfx/ringloss.ogg"

[22]
file = "resources/audio/sfx/ring.ogg"

[23]
file = "resources/audio/sfx/miniexplosion.ogg"

[24]
file = "resources/audio/sfx/transform.ogg"

[25]
file = "resources/audio/sfx/death.ogg"

[26]
file = "resources/audio/sfx/checkpoint.ogg"

[27]
file = "resources/audio/sfx/wrongway.ogg"

[28]
file = "resources/audio/sfx/spring.ogg"

[29]
file = "resources/audio/sfx/kaching.ogg"

[2A]
file = "resources/audio/sfx/warp.ogg"

