
[01]
file       = "resources/audio/bgm/titlescreen.ogg"

[02]
file       = "resources/audio/bgm/youre_my_hero.ogg"

[03]
file       = "resources/audio/bgm/transparenthighway.ogg"
loop-start = 45.459
loop-end   = 124.528

[04]
file       = "resources/audio/bgm/enjoythisworld.ogg"
loop-start = 0.049
loop-end   = 124.528

[05]
file       = "resources/audio/bgm/amazingaquarium.ogg"
loop-start = 11.009
loop-end   = 87.848

[06]
file       = "resources/audio/bgm/cybercity.ogg"
loop-start = 6.438
loop-end   = 67.231

[07]
file       = "resources/audio/bgm/walkin.ogg"
loop-start = 1.080
loop-end   = 17.233

[08]
file       = "resources/audio/bgm/chaoticcanyon.ogg"
loop-start = 8.799
loop-end   = 78.616
