[[levels]]
name = "Collision Test"
atlas = "resources/levels/R0/chunks.png"
tiles = "resources/levels/R0/tiles.tsx"
maps = [
      "resources/levels/R0/zone0.tmx"
]

[[levels]]
name = "Isolated Island"
atlas = "resources/levels/R1/chunks.png"
tiles = "resources/levels/R1/tiles.tsx"
maps = [
      "resources/levels/R1/zone0.tmx",
      "resources/levels/R1/zone1.tmx"
]

# [[levels]]
# name  = "Amazing Aquarium"
# atlas = ""
# tiles = ""
# maps  = []

[[levels]]
name = "Festival Freeway"
atlas = "resources/levels/R2/chunks.png"
tiles = "resources/levels/R2/tiles.tsx"
maps = [
     "resources/levels/R2/zone0.tmx",
     "resources/levels/R2/zone1.tmx"
]

[[levels]]
name  = "Wood"
atlas = "resources/levels/R3/chunks.png"
tiles = "resources/levels/R3/tiles.tsx"
maps  = [
      "resources/levels/R3/zone0.tmx",
      "resources/levels/R3/zone0.tmx"  # Replicated, for now
]

[[levels]]
name  = "Hidden Palace"
atlas = "resources/levels/R4/chunks.png"
tiles = "resources/levels/R4/tiles.tsx"
maps  = [
      "resources/levels/R4/zone0.tmx",
      "resources/levels/R4/zone0.tmx"
]

# [[levels]]
# name  = "Chaotic Corniche"
# atlas = ""
# tiles = ""
# maps  = []

# [[levels]]
# name  = "R5"
# atlas = ""
# tiles = ""
# maps  = []

# [[levels]]
# name  = "Cosmic Colony"
# atlas = ""
# tiles = ""
# maps  = []
