[[levels]]
name  = "Engine Test"
bgm   = "09"
atlas = "resources/levels/R0/chunks.png"
tiles = "resources/levels/R0/tiles.tsx"
maps = [
      "resources/levels/R0/zone0.tmx",
      "resources/levels/R0/zone1.tmx",
]

[[levels]]
name  = "Isolated Island"
bgm   = "03"
atlas = "resources/levels/R1/chunks.png"
tiles = "resources/levels/R1/tiles.tsx"
maps = [
      "resources/levels/R1/zone0.tmx",
      "resources/levels/R1/zone1.tmx"
]

[[levels]]
name  = "Speed Slider"
bgm   = "0B"
atlas = "resources/levels/R2/chunks.png"
tiles = "resources/levels/R2/tiles.tsx"
maps = [
     "resources/levels/R2/zone0.tmx"
]

[[levels]]
name  = "Wood"
bgm   = "04"
atlas = "resources/levels/R3/chunks.png"
tiles = "resources/levels/R3/tiles.tsx"
maps  = [
      "resources/levels/R3/zone0.tmx"
]

[[levels]]
name  = "Hidden Palace"
bgm   = "0A"
atlas = "resources/levels/R4/chunks.png"
tiles = "resources/levels/R4/tiles.tsx"
maps  = [
      "resources/levels/R4/zone0.tmx"
]

[[levels]]
name  = "Techno Tower"
bgm   = "06"
atlas = "resources/levels/R5/chunks.png"
tiles = "resources/levels/R5/R5.tsx"
maps  = [
      "resources/levels/R5/zone0.tmx"
]

# [[levels]]
# name  = "Amazing Aquarium"
# bgm   = "05"
# atlas = ""
# tiles = ""
# maps  = []

# [[levels]]
# name  = "Chaotic Corniche"
# bgm   = "08"
# atlas = ""
# tiles = ""
# maps  = []

# [[levels]]
# name  = "Cosmic Colony"
# atlas = ""
# tiles = ""
# maps  = []
