atlas      = "resources/sprites/knuckles.png"
frame_size = [ 60.0, 60.0 ]

[[animations]]
name           = "Idle"
frames         = [
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2,
    1, 1, 2, 2, 1, 1, 2, 2, 3, 3, 4, 5,
    6, 7, 8
]
frame_duration = 0.128
min_frame      = 47

[[animations]]
name           = "Walking"
frames         = [ 16, 17, 18, 19, 20, 21, 22, 23 ]
frame_duration = 0.128

[[animations]]
name           = "Running"
frames         = [ 24, 25, 26, 27 ]
frame_duration = 0.064

[[animations]]
name           = "Rolling"
frames         = [ 28, 32, 29, 32, 30, 32, 31, 32 ]
frame_duration = 0.064

[[animations]]
name           = "Skidding"
frames         = [ 33, 34 ]
min_frame      = 1

[[animations]]
name           = "Pushing"
frames         = [ 36, 37, 38, 39 ]
frame_duration = 0.25

[[animations]]
name           = "Crouching Down"
frames         = [ 14, 15 ]
frame_duration = 0.128
min_frame      = 1

[[animations]]
name           = "Looking Up"
frames         = [ 12, 13 ]
frame_duration = 0.128
min_frame      = 1

[[animations]]
name           = "Death"
frames         = [ 35 ]

