
[01]
file       = "resources/audio/bgm/titlescreen.ogg"

[02]
file       = "resources/audio/bgm/youre_my_hero.ogg"

[03]
file       = "resources/audio/bgm/transparenthighway.ogg"
loop-start = 45.459
loop-end   = 124.528

[04]
file       = "resources/audio/bgm/enjoythisworld.ogg"
loop-start = 0.049
loop-end   = 124.528

[05]
file       = "resources/audio/bgm/amazingaquarium.ogg"
loop-start = 11.009
loop-end   = 87.848
